/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/UxhRZICeys4
 */
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function Component() {
  return (
    <div className="min-h-screen flex flex-col bg-gradient-to-r from-blue-400 to-blue-600">
      <header className="flex items-center justify-between p-6 bg-blue-800 text-white">
        <h1 className="text-2xl font-bold">MBTI Test</h1>
        <nav className="flex items-center">
          <a className="mx-2 text-sm" href="#">
            Home
          </a>
          <a className="mx-2 text-sm" href="#">
            About
          </a>
          <a className="mx-2 text-sm" href="#">
            Contact
          </a>
        </nav>
      </header>
      <main className="flex-1 bg-blue-100 p-6">
        <div className="max-w-md mx-auto bg-white rounded-xl shadow-md overflow-hidden">
          <div className="flex justify-between p-4">
            <h2 className="text-lg font-medium">Chat</h2>
            <svg
              className=" h-4 w-4 text-blue-500"
              fill="none"
              height="24"
              stroke="currentColor"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              viewBox="0 0 24 24"
              width="24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path d="M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8" />
              <path d="M21 3v5h-5" />
              <path d="M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16" />
              <path d="M8 16H3v5" />
            </svg>
          </div>
          <div className="p-4 h-72 overflow-y-scroll">
            <div className="flex items-center space-x-4 p-2">
              <img
                alt="Chat Bot"
                className="rounded-full"
                height="40"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "40/40",
                  objectFit: "cover",
                }}
                width="40"
              />
              <p className="bg-blue-200 rounded-full py-2 px-4">Hello! Let's start the test.</p>
            </div>
          </div>
          <div className="border-t p-4">
            <form className="flex items-center">
              <Input className="flex-1" placeholder="Type your answer..." />
              <Button className="ml-2 bg-blue-500 text-white" type="submit">
                Send
              </Button>
            </form>
          </div>
        </div>
      </main>
      <footer className="p-6 bg-blue-800 text-white text-center">
        <p className="text-sm">© 2023 MBTI Test. All rights reserved.</p>
      </footer>
    </div>
  )
}
